# permissions for end users to edit memcaches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memcache-editor-role
rules:
- apiGroups:
  - caches.wise2c.com
  resources:
  - memcaches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - caches.wise2c.com
  resources:
  - memcaches/status
  verbs:
  - get
