# permissions for end users to view postgresqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: postgresql-viewer-role
rules:
- apiGroups:
  - databases.wise2c.com
  resources:
  - postgresqls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - databases.wise2c.com
  resources:
  - postgresqls/status
  verbs:
  - get
